# Generated by Django 5.2.8 on 2025-11-18 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Processing resources', 'Processing resources')], default='New', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='DownloaderRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloader', models.CharField(choices=[('Web page scraper', 'Web page scraper'), ('Jina AI reader using Jina API', 'Jina AI reader using Jina API')], max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChunkerRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Fixed size', 'Fixed size'), ('No chunking', 'No chunking')], max_length=1024)),
                ('size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('type', 'size')},
            },
        ),
        migrations.CreateModel(
            name='EmbedderRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('Ollama', 'Ollama'), ('Jina AI', 'Jina AI')], max_length=1024)),
                ('model_name', models.CharField(choices=[('jina-embeddings-v4', 'jina-embeddings-v4')], max_length=1024)),
            ],
            options={
                'unique_together': {('provider', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='ProcessorRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Simple RAG', 'Simple RAG')], max_length=1024)),
                ('chunker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.chunkerrow')),
            ],
            options={
                'unique_together': {('type', 'chunker')},
            },
        ),
        migrations.CreateModel(
            name='ResourceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Downloaded', 'Downloaded'), ('Scraped', 'Scraped'), ('Error', 'Error')], default='New', max_length=1024)),
                ('scraped_content', models.TextField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='common.conversationrow')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.resourcerow')),
            ],
        ),
        migrations.CreateModel(
            name='TextExtractorRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('Jina AI', 'Jina AI'), ('Ollama', 'Ollama')], max_length=1024)),
                ('model_name', models.CharField(choices=[('ReaderLM-v2', 'ReaderLM-v2')], max_length=1024)),
            ],
            options={
                'unique_together': {('provider', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='ConversationConfigRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.conversationrow')),
                ('downloader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.downloaderrow')),
                ('embedder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.embedderrow')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.processorrow')),
                ('text_extractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.textextractorrow')),
            ],
        ),
    ]
