# Generated by Django 5.2.8 on 2025-11-16 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloaderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloader', models.CharField(choices=[('Web page scraper', 'Web Scraper')], max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChunkerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Fixed size', 'Fixed'), ('No chunking', 'No Chunk')], max_length=1024)),
                ('size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('type', 'size')},
            },
        ),
        migrations.CreateModel(
            name='EmbedderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ollama', 'Local'), ('jina', 'Jina Api')], max_length=1024)),
                ('model_name', models.CharField(choices=[('jina-embeddings-v4', 'Jina Embeddings V4')], max_length=1024)),
            ],
            options={
                'unique_together': {('provider', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='ProcessorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Simple RAG', 'Simple Rag')], max_length=1024)),
                ('chunker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.chunkertable')),
            ],
            options={
                'unique_together': {('type', 'chunker')},
            },
        ),
        migrations.CreateModel(
            name='ResourceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('url', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Download in progress', 'Download In Progress')], default='New', max_length=1024)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.resourcetable')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('Processing resources', 'Processing Resources')], default='NEW', max_length=1024)),
                ('resources', models.ManyToManyField(to='common.resourcetable')),
            ],
        ),
        migrations.CreateModel(
            name='TextExtractorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('jina', 'Jina Api'), ('ollama', 'Local')], max_length=1024)),
                ('model_name', models.CharField(choices=[('ReaderLM-v2', 'Reader Lm V2')], max_length=1024)),
            ],
            options={
                'unique_together': {('provider', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='ConversationConfigTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.conversationtable')),
                ('downloader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.downloadertable')),
                ('embedder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.embeddertable')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.processortable')),
                ('text_extractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.textextractortable')),
            ],
        ),
    ]
