# Generated by Django 5.2.8 on 2025-11-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationtable',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
