# Generated by Django 5.2.8 on 2025-11-20 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerow',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Downloaded', 'Downloaded'), ('Scraped', 'Scraped'), ('Error', 'Error'), ('Processed', 'Processed')], default='New', max_length=1024),
        ),
        migrations.CreateModel(
            name='EventLogRows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Conversation created', 'Conversation created'), ('Resource added', 'Resource added')], max_length=1024)),
                ('entity_id', models.CharField(max_length=1024)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.conversationrow')),
            ],
        ),
    ]
