# Generated by Django 5.2.8 on 2025-11-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChunkerTable',
            new_name='ChunkerRow',
        ),
        migrations.RenameModel(
            old_name='ConversationConfigTable',
            new_name='ConversationConfigRow',
        ),
        migrations.RenameModel(
            old_name='ConversationTable',
            new_name='ConversationRow',
        ),
        migrations.RenameModel(
            old_name='DownloaderTable',
            new_name='DownloaderRow',
        ),
        migrations.RenameModel(
            old_name='EmbedderTable',
            new_name='EmbedderRow',
        ),
        migrations.RenameModel(
            old_name='ProcessorTable',
            new_name='ProcessorRow',
        ),
        migrations.RenameModel(
            old_name='ResourceTable',
            new_name='ResourceRow',
        ),
        migrations.RenameModel(
            old_name='TextExtractorTable',
            new_name='TextExtractorRow',
        ),
    ]
